// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/achievements" | "/[locale]/auth/sign-in" | "/[locale]/auth/sign-up" | "/[locale]/cases" | "/[locale]/cases/[case_id]" | "/[locale]/cases/[case_id]/debrief" | "/[locale]/contact" | "/[locale]/dashboard" | "/[locale]/faq" | "/[locale]/learn" | "/[locale]/learn/[slug]" | "/[locale]/mission/[case_id]" | "/[locale]/privacy" | "/[locale]/redeem" | "/[locale]/terms"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/achievements": { "locale": string; }
  "/[locale]/auth/sign-in": { "locale": string; }
  "/[locale]/auth/sign-up": { "locale": string; }
  "/[locale]/cases": { "locale": string; }
  "/[locale]/cases/[case_id]": { "locale": string; "case_id": string; }
  "/[locale]/cases/[case_id]/debrief": { "locale": string; "case_id": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/faq": { "locale": string; }
  "/[locale]/learn": { "locale": string; }
  "/[locale]/learn/[slug]": { "locale": string; "slug": string; }
  "/[locale]/mission/[case_id]": { "locale": string; "case_id": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/redeem": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
